name: "Bump version"
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      
      - uses: harvidsen/bumpver-action@v1.0
        with:
          args: --minor --dry

      - uses: harvidsen/bumpver-action@139a871e17967a50b56f3380a4e313d34a4b718f
        with:
          args: --major --dry
