name: "Bump version"
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      
      - uses: harvidsen/bumpver-action@e6ece92fc2a092b04b281c6b46a164ffdd6f8383
        with:
          args: --minor --dry

      - uses: harvidsen/bumpver-action@e6ece92fc2a092b04b281c6b46a164ffdd6f8383
        with:
          args: --major --dry
